# Generated by Django 4.0.1 on 2022-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('car', models.IntegerField()),
                ('rent', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=70)),
                ('imagepath', models.CharField(max_length=250)),
            ],
        ),
    ]
